-- 코드를 입력하세요
SELECT f.FLAVOR
FROM FIRST_HALF f
INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL
            FROM JULY
            GROUP BY FLAVOR) AS j
ON f.FLAVOR=j.FLAVOR
GROUP BY f.FLAVOR
ORDER BY SUM(TOTAL+f.TOTAL_ORDER) DESC
limit 3