-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, sum(b.price) as TOTAL_SALES
FROM USED_GOODS_BOARD b, USED_GOODS_USER u
WHERE b.WRITER_ID=u.USER_ID AND STATUS = 'DONE'
GROUP BY b.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES