SELECT m.MEMBER_NAME, r.REVIEW_TEXT, date_format(r.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE m INNER JOIN REST_REVIEW r
ON m.MEMBER_ID=r.MEMBER_ID
WHERE m.MEMBER_ID = (   
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(REVIEW_ID) desc
        limit 1
)
ORDER BY REVIEW_DATE, r.REVIEW_TEXT